<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [ ]:

# Your code here


### 1.2 Named functions that don’t return

In [ ]:

# Your code here


### 1.3 Anonymous functions

In [4]:
a = lambda x: x + 3
b = lambda y: y*3
print(a(b(1)))
print(b(a(1)))
print(a(b(a(b(a(b(1)))))))
print(b(a(b(a(b(a(1)))))))

6
12
66
144


### 1.4 Optional arguments

In [ ]:

# Your code here


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

When the first `if` statement is not fulfilled, the first `return` statement is not fired and Python will proceed to the next line. The function then proceeds to the second `return` statement which will always return the argument {name}.

## Exercise 2 :  Calculator functions

In [20]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
z=np.array([0,0,0,0,0])
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    if type(y) in [int,float] and y == 0:
        return 'Division by zero!'
    if type(y) in [list,tuple,np.ndarray] and 0 in y:
        return 'Division by zero!'
    return x/y
print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))
print(divide(1,0))
print(divide(1.0,0.0))
print(divide(y,z))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
Division by zero!
Division by zero!
Division by zero!


## Exercise 3 :  max_info() with NumPy

In [2]:
import numpy as np
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return [max(numbers),numbers.index(max(numbers))]
print(max_info(numbers))

def max_info(numbers):
    arr = np.array(numbers)
    return [arr.max(),arr.argmax()]
print(max_info(numbers))

[83, 2]
[83, 2]
