<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [3]:
x = 10
assert x >= 0, "x is becoming negative!"

### 1.2 try-except

In [ ]:

# Your code here


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [ ]:

# Your code here


### 2.2 Docstrings

In [ ]:

# Your code here


### 2.3 Function are first class citizens

In [ ]:

# Your code here


### 2.4 More unpacking

In [ ]:

# Your code here


## Exercise 1 :  A better calculator I

In [15]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def check(input):
    assert type(input) not in [str,list,tuple,dict], print('Invalid input!')
def add(x,y):
    check(x)
    check(y)
    return x+y
def subtract(x,y):
    check(x)
    check(y)
    return x-y
def multiply(x,y):
    check(x)
    check(y)
    return x*y
def divide(x,y):
    check(x)
    check(y)
    assert (type(y) in [int,float] and y != 0) or (type(y) in [list,tuple,np.ndarray] and 0 not in y), print('Division by zero!')
    return x/y
print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(1,0)) #Is this function required to continue after the error?


[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
Division by zero!


AssertionError: None

## Exercise 2 :  A better calculator II

In [20]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def add(x,y):
    try:
        return x+y
    except:
        print('Invalid Input!')
def subtract(x,y):
    try:
        return x-y
    except:
        print('Invalid Input!')
def multiply(x,y):
    try:
        return x*y
    except:
        print('Invalid Input!')
def divide(x,y):
    try:
        return x/y
    except ZeroDivisionError:
        print('Division by Zero!')
    except:
        print('Invalid Input!')
print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(1,0))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
Division by Zero!
None
