<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [ ]:

# Your code here


### 1.2 Subsetting by masking (Arrays only)

In [2]:
import numpy as np
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = np_array > 3
print(my_mask)

np_array[my_mask]

[False False False  True  True  True  True  True  True  True]


array([ 4,  5,  6,  7,  8,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [ ]:

# Your code here


### 1.4 Indexing & Slicing 2D Arrays

In [ ]:

# Your code here


### 1.5 Growing lists

In [ ]:

# Your code here


## 2 Some loose ends

### 2.1 Tuples

In [ ]:

# Your code here


### 2.2 Be VERY careful when copying

In [ ]:

# Your code here


## Exercise 1 :  Total recall?

|**Term**|**Brief Description**|
|:-------|--------------------:|
|Subsetting|Filtering a list/array to show selected elements|
|Indexing|Pulling a specific element(s) from a list/array|
|Slicing|Cutting out a segment of the list/array|
|Masking|Creating a filter that tells an array which elements to display|

## Exercise 2 :  Show me the ‘odd’ letters

In [6]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
step_1 = np_array_2d[:,0]
print(step_1)
step_2 = step_1.astype(int)
print(step_2)
step_3 = step_2 % 2
print(step_3)
step_4 = step_3 == 1
print(step_4)
np_array_2d[step_4,1]

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')